name = "Starlight Minecraft"
author = "Starlight"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e7ff720db9dbc19e8612bb8e325dd0171a069793ae3ffee437bfd9d573440c8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
