name = "Starlight Minecraft"
author = "Starlight"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c75868aa43b9ab4a457a3455f8a1b18374adbc847cd6dbe7aa92f8a30054d41"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
