name = "Starlight Minecraft"
author = "Starlight"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ba9224265d24d48c8f9c2a641575d4d4484c1c6d56184f3d2e86fb470472082"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
